- locales/da.yml
- locales/de.yml
- locales/es.yml
- locales/fr.yml
- locales/no.yml
- locales/se.yml
Cherry picked from current branding
> better enrollment failure message

- templates/form_dankort_acs.liquid
> Dankort ACS expect form params in ISO-8859-1

- templates/form/klarna.liquid
Fixes QuickPay/payment#524
Klarna has requested that Business number is added to nin-number label
> Klarna nin_number field label changed by to Klarna request

- templates/form/bitcoin.liquid
- templates/form/klarna.liquid
- templates/form/mobilepay.liquid
- templates/form/paypal.liquid
- templates/form/sofort.liquid
- templates/form/swish.liquid
- templates/form/viabill.liquid
https://github.com/QuickPay/standard-branding/blob/master/templates/form.liquid#L2
> Form errors template included for all sub-templates in

- templates/form/resurs.liquid
> Added resurs template

- templates/form/mobilepay_subscriptions.liquid
redirect-url should no longer be broken
> Added hidden fields for mps-backend redirect url

- templates/form/swish.liquid
#77 
accept patterns like +07 123456, +07-123456, 07123456, 07 123456, 07-123456,
> accepting variation of phone number for swish

- templates/success.liquid
#66 
Changed success message for card and subscription as mention in #66
> 66 changed success message for card and subscription

- templates/waiting.liquid
#68 
Rephraze "please wait" to "The process may take some time".
> updated please wait text

- README.md
- templates/form/card.liquid
#70 
**Pre-deployment task:**
[https://github.com/QuickPay/payment/pull/921](https://github.com/QuickPay/payment/pull/921)
> Prefill card name if invoice_address[name] is present

- templates/form/bancontact.liquid
- templates/form/przelewy24.liquid
fixes QuickPay/ppro-backend#69
requires QuickPay/payment#1011 and an additional payment PR which adds the Form
> Add branding for ppro

- templates/form/bancontact.liquid
- templates/form/przelewy24.liquid
Fixes #90 
- Changed the test so it is consistent with other payment methods
> Capitalising the PPRO payment methods

- templates/form/bancontact.liquid
- templates/form/przelewy24.liquid
> PPRO payment methods now apply parameters in redirect url

- templates/form/blik.liquid
> BLIK Implementation

- templates/form/unzer-pay-later-direct-debit.liquid
Add payment-method `Direct Debit` for Unzer Pay Later
> Add Unzer-pay-later Direct Debit

- templates/form/unzer_pay_later_invoice.liquid
Added payment-method Invoice for Unzer Pay Later
> Implement Unzer Pay Later: invoice

- templates/payment_methods_list.liquid
Reverts QuickPay/standard-branding#45
> Revert "adds Google Pay handling"

- templates/form/unzer_pay_later_invoice.liquid
fixes QuickPay/unzer-pay-later-backend#41 when deployed with payment
Adds:
* Checkbox for user consent and agreement with Unzer T&C
> Added T&C to upl template

- templates/form/unzer_pay_later_invoice.liquid
fixes QuickPay/unzer-pay-later-backend#44
* Adds the threatmatrix requirements for unzer pay later invoice
* Makes name readonly
* Makes email readonly if given
> Add threatmatrix upl invoice

- templates/form/unzer_pay_later_direct_debit.liquid
* Remove "-" from unzer pay later direct debit to match naming schema.
* Set IBAN and BIC as required fields
* Email, First name and Last name is read only 
* Add hidden `upl_session_id` field 
* Add `Bank account holder` field 
* Add T&C consent
> Adjust Unzer Pay Later Direct Debit

- templates/form/unzer_pay_later_direct_debit.liquid
- templates/form/unzer_pay_later_invoice.liquid
Show validation errors for invalid day of birth and/or iban on unzer-pay-later form(s)
> Show validation errors on unzer-pay-later forms

- templates/form/unzer_pay_later_direct_debit.liquid
- templates/form/unzer_pay_later_invoice.liquid
Terms and condition text on unzer-pay-later is now left aligned
> Left align T&C Text on unzer-pay-later

- templates/form/paypalpayments.liquid
- new form/liquid file added for paypal payments
> paypalpayments form added

- stylesheets/paymentwindow.css
- templates/form/card.liquid
Added reservation notice to payment window. 
The notice will only display if set by the merchant in their branding configs.
> Added reservation notice to payment form

- templates/selector.liquid
Add translation tag for "Select Payment Method". It did not have a translation tag before.
After merge, this string needs translation.
> Add translation tag

- templates/form/vmp_epayment.liquid
- templates/payment_methods_list.liquid
* Added vmp-epayment as new payment-method
* Show different logo for payment-method vmp-payment depending on the transaction's currency.
> Add vmp epayment
